version: '3.8'

services:
  rack_token_bucket:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      context: .
      dockerfile: Dockerfile.rack_token_bucket
    ports:
      - "9998:9998"
    container_name: rack_token_bucket
  rack_fixed_window_counter:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      context: .
      dockerfile: Dockerfile.rack_fixed_window_counter
    ports:
      - "9997:9997"
    container_name: fixed_window_counter
  rack_sliding_window_log:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      context: .
      dockerfile: Dockerfile.rack_sliding_window_log
    ports:
      - "9996:9996"
    container_name: sliding_window_log
  redis:
      image: redis
      ports:
        - "6380:6379" # Using port 6380 externally and the default Redis port 6379 internally
      container_name: redis_service

